env:
  - CGO_ENABLED=1
builds:
  - id: build-windows-386
    env:
      - CC=i686-w64-mingw32-gcc
      - CXX=i686-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - 386
    ldflags:
      - '-extldflags "-static -s -w"'
  - id: build-windows-amd64
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - '-extldflags "-static -s -w"'
  - id: build-linux-386
    goos:
      - linux
    goarch:
      - 386
    ldflags:
      - '-extldflags "-static -s -w"'
  - id: build-linux-amd64
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - '-extldflags "-static -s -w"'
