project_name: my_dump_tool
env:
  - CGO_ENABLED=1
builds:
  - id: build-windows-amd64
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - '-extldflags "-static -s -w"'
